### ISSUE TITLE
wallet isssue

### ISSUE THREAD

**Issue by Dannywat61** [alephium/alephium-frontend#1002]
my alphieum wallet wont connect state is currently off line why ?

**Comment by Gordonhills** [comment]
Hello @Dannywat61 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ALE07638
Please see the link below to our dedicated support line:
[Alephium Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
