### ISSUE TITLE
Disable biometric auth when the fingerprints or face data have been changed

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#11]
In order to increase security and do better than most crypto wallets, in case of a change in on-device biometric settings :
1)  Let's deactivate biometric authentication;
2) Fallback to pin and show a popup asking the user to reactivate the biometric option if needed.

I personally like the wording used by Authy:

![image](https://user-images.githubusercontent.com/6715943/183886563-6a50efc9-97f7-41a8-85b6-ab3cdd0792d1.png)

**Comment by nop33** [comment]
It was implemented! https://github.com/alephium/alephium-frontend/pull/256

Closing
