### ISSUE TITLE
Transaction requests from WalletConnect do not always show up

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#110]
Users reports:

> Something has been glitching when it comes to signing under WalletConnect (this is true for desktop and mobile wallet) - the signing request doesn't always come up.. it started misbehaving last week for me on mobile wallet. I've been helping users get around it by recommending the extension wallet. It happened to multiple people. It was so bad last night I had to give up on the mobile wallet and use kiwi again:(

> It also happens with desktop.

> It works 100% of the time with extension wallet.

### Steps to reproduce

Users reports:
> go to ayin.app, login, and do something requiring signing. (half the time when switching back to wallet the signing request isn't there)

> If you wait 15 minutes it works again but if you try to do multiple swaps in a row it acts up. I was having to reconnect to complete each swap

**Comment by diomark** [comment]
Just tested this again on mobile wallet and same issue. (I've only seen the issue on desktop one time? it's usually the mobile wallet)

**Comment by nop33** [comment]
I've been testing today both desktop wallet and mobile wallet and I can't reproduce this issues. I always get the sign requests from ayin. I tested both the production apps, as well as the latest development code. I'll keep trying...

**Comment by mvaivre** [comment]
This is probably fixed now. cc @nop33

**Comment by nop33** [comment]
Closing since our community has not been complaining about this anymore, seems like the last update fixed it. Will re-open if needed.
