### ISSUE TITLE
Cannot fetch price from CoinGecko

### ISSUE THREAD

**Issue by Stas724** [alephium/alephium-frontend#115]
**Describe the bug**
Whenever I open up the Alephium Wallet App and look at my "Value today" is shows - $ value.

**To Reproduce**
1. Login to account
2. Look at Value today

**Expected behavior**
This started to happen about a week ago or so. I have reinstalled my windows thinking it could of been my operating system. Seems like this must be server side or app side.

**Screenshots**
https://ibb.co/cC4LSDR

**Environment**
 - Windows 11
 - 22H2

**Additional context**
Doesn't effect function the app, but inconvenience because i have to manually calculate todays value. 

## Subtasks

- [ ] #243
- [ ] #244
- [x] #294

**Comment by nop33** [comment]
Other users reported this yesterday as well, seems that the explorer is also affected, also mobile wallet.

https://discord.com/channels/747741246667227157/1176209538349809765

<img width="1288" alt="image" src="https://github.com/alephium/alephium-frontend/assets/1579899/e3e4c0f1-fcc4-417d-852f-35e9e6de5fd1">

**Comment by Stas724** [comment]
@nop33 

Any news/updates/progression of this issue?

Thanks!

**Comment by nop33** [comment]
Hello @Stas724 , no, there are no updates regarding this yet.

**Comment by Ryanmr88** [comment]
It happens to me on any device that connects to my local network - its not just the mobile wallet, same with desktop wallet, explorer etc.. 

Not an isolated issue 

https://x.com/Shigeo808/status/1727745029903683675?s=20

**Comment by mvaivre** [comment]
Thanks @Ryanmr88 for the details. Yes, the limit is based on IP. We're going to try and reduce the number of calls we need to do in order to fetch the prices.

**Comment by nop33** [comment]
Fixed in the latest versions of the wallets and explorer. Closing.
