### ISSUE TITLE
Excessive lock screen fingerprint requests

### ISSUE THREAD

**Issue by diomark** [alephium/alephium-frontend#127]
Android (pixel 7 pro) , play store build

Every time I switch back to the wallet, it asks for a fingerprint. Even if I had just been in the wallet 1 second ago.

Settings has an option "Request authentication for important actions" - but there really should be an option to relax authentication unless you're doing an important action. 

Requesting authentication first time I access the wallet in a while makes sense, and then subsequently when signing something. But asking everytime (especially when I'm just switching to browser/right back 2 seconds later) is excessive. 

Please add an option to only request when first opening the wallet. OR 

This seems to be the default behavior for metamask btw. it doesn't ask everytime. only the first time I open it (or if it's been closed/hasn't been open in a while). so perhaps alph wallet should just behave this way (?)

Of course it should ask everytime you sign/send/etc.

**Comment by nop33** [comment]
It's worth mentioning that when I was diving into the Metamask codebase I noticed that they have a setting for this. The default is `30` seconds. Other options are:
- Immediately
- 5s
- 15s
- 30s
- 60s
- 5m
- 10m
- Never

cc @mvaivre

**Comment by diomark** [comment]
I just tested in my own banking app, and unless i've hit the timeout (which for them is 15 minutes I think), it doen'st re-prompt me again just for switching back and forth with another app.

**Comment by mvaivre** [comment]
If we switch from pin to password, this will definitely be needed. 
Let's follow Metamask's approach on this.
