### ISSUE TITLE
Incomplete list of transactions on MW

### ISSUE THREAD

**Issue by VDAODAO** [alephium/alephium-frontend#137]
**Describe the bug**
Only some of the transactions are shown in the list of transactions.
for ref: https://alephium.slack.com/archives/C026MHDJD2N/p1701250905522969

**To Reproduce**

1. Go to your list of tx in the MW
2. Compare to explorer list of tx
3. See that not all tx are present

**Expected behavior**
All tx should be in the tx history, it even says "you've reached the end of history"

**Screenshots**
see attached: 

explorer address - https://explorer.alephium.org/addresses/19P5mf2XkwhA98qa6fiSsrmYr11zFNDuh3FWFmwZBY16Q

| | | |
| ----- | ----- | ----- |
| ![IMG_7562](https://github.com/alephium/alephium-frontend/assets/42373571/91fddc5c-87bb-4391-94db-4cb3391de303) | ![IMG_7561](https://github.com/alephium/alephium-frontend/assets/42373571/7857a16b-6aa4-4a17-ac59-a3d147eb66d8) |  ![IMG_7560](https://github.com/alephium/alephium-frontend/assets/42373571/8f98d1df-a203-4e53-bb6a-d984668afaf4) |

**Environment**

- i0S
- first public version

**Additional context**
:) <3

**Comment by nop33** [comment]
I managed to reproduce this with this address on testnet: https://testnet.alephium.org/addresses/1DrDyTr9RpRsQnDnXo2YRiPzPW4ooHX5LLoqXrqfMrpQH?p=3

The first 2 pages load correctly on the mobile wallet. But then it gives me an "You reached the end"
