### ISSUE TITLE
[EPIC] Port explorer logic & display to the wallets to better display failed transaction

### ISSUE THREAD

**Issue by MaudSimon** [alephium/alephium-frontend#138]
When a transaction fails, it is currently not clearly displayed in the mobile & desktop wallets (amounts are white VS successful transactions are colored). However, it is very cleary/explicitly shown in the explorer. 

**Describe the solution you'd like**
Port explorer logic & display to the wallets to better display failed transaction

## Subtasks
- [ ] #335
- [ ] #336

**Comment by nop33** [comment]
@MaudSimon @mvaivre do we have any testnet wallet that has some failed transactions?
