### ISSUE TITLE
Improve error display

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#146]
When WalletConnect errors occur in the mobile wallet, the displayed error message gets cleared too fast. The attention of the user might be in the mobile browser or the desktop browser and not necessarily in the mobile wallet. When their attention switches back to the mobile wallet, the error might have already been hidden.

I propose that we create a "close" button (like an "X" icon in the corner of the displayed message).

@mvaivre thoughts?

**Comment by nop33** [comment]
In https://github.com/alephium/alephium-frontend/commit/3c4ad1eb2d880889fe4d9268f25ede5735440259 I increased the time an error is displayed by default. The user can tap on the error to hide it. I think that's a good first step.

**Comment by mvaivre** [comment]
I agree: we should add the ability to create "static" errors that the users need to close manually. We could simply allow setting the duration to `Infinity` and in that case not running the timeout.
