### ISSUE TITLE
VSCode does not display linting errors (when opening the monorepo root)

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#155]
I'll take some time to describe this issue later. I discovered this when I added a new dependency into a hook and I didn't get a warning that I need to add the dependency in the dependency array.

**Comment by mvaivre** [comment]
Sounds like the issue I had a couple of weeks ago. Are you working on the full mono repo or on a sub repo ?

**Comment by nop33** [comment]
I have the monorepo root open in my editor
