### ISSUE TITLE
Alephium Solo Mining Explorer Node Sync Issue

### ISSUE THREAD

**Issue by Stas724** [alephium/alephium-frontend#204]
[](https://ibb.co/PZ2YZvM)

I have been having issues setting up a full node on my machine. It's been running for exactly 72 hours and manages to only complete 1GB worth of DB. Looks like it gets stuck / hangs here each time. 

Steps I have done

 -  format drive C:/ & Reinstall windows 10 pro x64 clean

 - installed Java 17 

 - factor reset my gateway

 - I even did an extra mile and purchased a new gateway just in case if there was something wrong with mine. (Still same result)

What could be the cause of my machine to not download the db of the explorer to sync up. I know the db is roughly shy of 75GBs

**Comment by Stas724** [comment]
![image](https://github.com/alephium/alephium-frontend/assets/92892178/ed2b5684-f399-44ec-a141-98cf7db26cfc)

**Comment by Stas724** [comment]
@nop33 would you be able to guide me?

**Comment by nop33** [comment]
Hello @Stas724! I would advise you do ask for help on the Discord channels, you will find better support there. There is a dedicated support channel, as well as a full node one and mining. Cheers!
