### ISSUE TITLE
Auto-update from 2.1.5 to 2.1.6 doesn't work on macOS

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#206]
The 2.1.5 version was signed with @killerwhile's certificates (which by now are expired). @killerwhile, @mvaivre, and @nop33 had the idea to sign the 2.1.6 with both our new and the old certificates. However, this idea didn't work, cause when I tried to update my mac app from 2.1.5 to 2.1.6 I got this error:

```
Error: Code signature at URL file:///[...]/Alephium.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

**Comment by nop33** [comment]
There seems to be a [workaround](https://github.com/electron-userland/electron-builder/issues/4166#issuecomment-548388379).

**Comment by nop33** [comment]
1. Specify new "designated requirement" that covers both the old and the new code signing identity.
2. Sign with old certificates (they are expired, this might be a problem)
3. Release 2.1.6 so that the auto-update will work since the code requirements are met
4. Update designated requirement so that it covers only the new code signing identity.
5. Sign with new certificates
6. Release 2.1.7

This is the diff between the old and the new "designated requirement" (notice the last word):

```diff
old: designated => identifier "org.alephium.alephium-wallet" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = U55BZ92P8B
new: designated => identifier "org.alephium.alephium-wallet" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = Z3J8P4JW24
```

This info was retrieved by:

```shell
codesign -d -v -r - /Applications/Alephium.app #2.1.5
codesign -d -v -r - /Users/ilias/Desktop/Alephium.app # 2.1.6
```

**Comment by nop33** [comment]
I tried to specify the following designated requirements:

```
designated => identifier "org.alephium.alephium-wallet" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and (certificate leaf[subject.OU] = U55BZ92P8B or certificate leaf[subject.OU] = Z3J8P4JW24)
```

but signing failed: `nested code is modified or invalid`

```
  • signing         file=dist/mac-universal/Alephium.app identityName=Developer ID Application: Benoit Perroud (U55BZ92P8B) identityHash=7FB820A4F7BF820B3089420B443326A58C85DCFA provisioningProfile=none
  ⨯ Command failed: codesign --verify --deep --strict --verbose=2 /Users/runner/work/alephium-frontend/alephium-frontend/apps/desktop-wallet/dist/mac-universal/Alephium.app
/Users/runner/work/alephium-frontend/alephium-frontend/apps/desktop-wallet/dist/mac-universal/Alephium.app: nested code is modified or invalid
  failedTask=build stackTrace=Error: Command failed: codesign --verify --deep --strict --verbose=2 /Users/runner/work/alephium-frontend/alephium-frontend/apps/desktop-wallet/dist/mac-universal/Alephium.app
/Users/runner/work/alephium-frontend/alephium-frontend/apps/desktop-wallet/dist/mac-universal/Alephium.app: nested code is modified or invalid

```

**Comment by nop33** [comment]
I can't figure this out, I keep getting `nested code is modified or invalid` even if I just copy+paste the result of `codesign -d -v -r - /Users/ilias/Desktop/Alephium.app` into the `requirements.rqset` file. Then I thought I might not be putting the file in the right location, but I tried the `build`, `assets`, `public` folders as well as in the root of the project, but none of them worked.

**Comment by mvaivre** [comment]
Thanks for the reports @nop33. @killerwhile, any idea? If not, we'll ask our user base to manually download the next version (which we would really like to avoid, so any ideas are more than welcome!)

**Comment by nop33** [comment]
We decided to go ahead and release and simply ask users to manually install. Closing issue.
