### ISSUE TITLE
[MW] Fix header and content position in Addresses/Contacts screens

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#22]
See these issues for details:
- https://github.com/alephium/mobile-wallet/issues/250
- https://github.com/alephium/mobile-wallet/issues/277

**Comment by mvaivre** [comment]
We can try fixing calculations, or just go for a refactored / simpler BaseHeader.

**Comment by nop33** [comment]
I would go for a proper solution if possible (BaseHeader)
