### ISSUE TITLE
[DW] Wrong decimal display for token-list assets (in AssetBadge)

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#230]
The assets' value seems to be wrongly displayed for assets with `decimals` equal to 0.

**Comment by MaudSimon** [comment]
<img width="946" alt="image" src="https://github.com/alephium/alephium-frontend/assets/52083111/58b759fe-c34b-4268-bd71-ec5c25aec10d">
Sorry to re-open, just want to mention that someone just reported that bug with a token that didn't have decimal = 0.

**Comment by nop33** [comment]
It's probably the same issue, let's see if it gets fixed once we release the next version.
