### ISSUE TITLE
Addresses & contacts

### ISSUE THREAD

**Issue by m-javdan** [alephium/alephium-frontend#235]
hi
i cant remove address, how can remove addresses ?

**Comment by nop33** [comment]
There is no option to remove addresses at the moment. We have a feature request to hide addresses: https://github.com/alephium/alephium-frontend/issues/52. Feel free to upvote it or write a comment! Closing as duplicate.

**Comment by m-javdan** [comment]
Deleting the address is very important because I may use the wrong address when sending and I will suffer a financial loss.

**Comment by nop33** [comment]
What do you mean by deleting an address?

**Comment by m-javdan** [comment]
What I mean is that in the addresses section:
I created a new address and I can't delete it and my problem is that when I want to send coins to an address I may make a mistake and choose the wrong address so I want to remove the additional address and this possibility in the software do Does not exist.

**Comment by nop33** [comment]
You would never suffer financial loss by sending funds to an address of yours. We will implement the feature of hiding addresses you have generated so that you don't see them in the addresses section.
