### ISSUE TITLE
Icon inconsistent with displayed message on Mobile wallet

### ISSUE THREAD

**Issue by MaudSimon** [alephium/alephium-frontend#263]
**Describe the bug**
Reported on Discord: https://discord.com/channels/747741246667227157/878206973781368842/1195897088714747904

On mobile wallet: 
When a user rejects a dApp Tx/interaction, the message says rejected but the icon is a green tick. 

<img width="645" alt="image" src="https://github.com/alephium/alephium-frontend/assets/52083111/0083e0cd-233a-4cba-a9f6-d7f4f0a79e57">

**To Reproduce**
Reject a dApp Tx on mobile wallet 

**Expected behavior**
I expect the icon to match the message (so probably a red cross)

**Comment by nop33** [comment]
This is intended. The user chose to reject the app so the rejection was successful :D

**Comment by mvaivre** [comment]
We'll add a "neutral" (info) type to make this clearer.
