### ISSUE TITLE
Update expired Windows certificate and release workflow

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#265]
Microsoft changed the way they provide code-signing certificates. They want the signing to be FIPS-140 compliant. That's a very restrictive security standard. Our current release workflow that uses `electron-builder` needs to be updated.

Related issues:
- https://github.com/electron-userland/electron-builder/issues/7605
- https://github.com/electron-userland/electron-builder/issues/7895

**Comment by nop33** [comment]
This might be helpful: https://github.com/electron-userland/electron-builder/issues/6158#issuecomment-899798533
Also related, electron-builder windows config: https://www.electron.build/configuration/win
Especially this: **How do delegate code signing?** https://www.electron.build/configuration/win#how-do-delegate-code-signing

**Comment by nop33** [comment]
Ledger is [utilizing the `sign` hook](https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/electron-builder.yml#L41) of `electron-builder` with [their own script](https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/scripts/sign-windows.js).

**Comment by nop33** [comment]
## Summary of current status

Our app's executables are being built using `electron-builder` as a step in our `release-desktop.yml` GitHub workflow (through the [`nop33/action-electron-builder`](https://github.com/alephium/alephium-frontend/issues/269) GitHub action). That's how the following release files get generated:
- `.exe`: executable binary
- `.exe.blockmap`: stores delta between version updates
- `.exe.checksum`: well, checksum, dah
- `latest.yml`: used by the updater to refer to the latest version, .exe, and hash of .exe

@killerwhile has implemented the signing of the above `.exe` as an additional step of our `release-desktop.yml` GitHub workflow using the GitHub action `sslcom/esigner-codesign`.

## Problem

The `.exe.blockmap`, `.exe.checksum` and `latest.yml` are created **BEFORE** the signed Windows `.exe` file is created: https://github.com/alephium/alephium-frontend/issues/272

## Possible solution

Thankfully, `electron-builder` [exposes the `sign` hook](https://www.electron.build/tutorials/code-signing-windows-apps-on-unix#integrate-signing-with-electron-builder) in their config. This allows us to create a `signWindows.js` file that will be used to sign the `.exe` **BEFORE** creating all release-additional files:

```ts
// package.json

"build:{
  "win": {
    "sign": "signWindows.js",
  },
},
```

So, the idea is: 

### 💡 Don't use the `sslcom/esigner-codesign` GitHub action as a step of our GitHub workflow and create a JS file to do the signing.

This is what [this person](https://github.com/electron-userland/electron-builder/issues/6158#issuecomment-899798533) has done.

I started working on this idea by creating a `.signWindows.js` file and hooking it up to the `electron-builder` config (see this WIP PR: https://github.com/alephium/alephium-frontend/pull/276)

I am stuck at this problem: How do I make the `CodeSignTool-v1.3.0-windows` executable available to the script? It's `333Mb` big and I don't think we should commit that to our repo... 

<details><summary>Related sources</summary>

- `electron-builder` Windows config: https://www.electron.build/configuration/win
   - especially **How do delegate code signing?**: https://www.electron.build/configuration/win#how-do-delegate-code-signing
- https://github.com/electron-userland/electron-builder/issues/6158#issuecomment-899798533

</details>

**Comment by killerwhile** [comment]
The second option is also downloading the eSigner tool, but a version which is only 15MB. The _official_ version seems to be here: https://github.com/SSLcom/eSignerCKA/releases
