### ISSUE TITLE
[EPIC] Centralise loading of clients and initial data at the app start

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#274]
Wait for clients and base data to be loaded before actually showing the UI.

Create a nice loader animation. Reuse the idea of displaying welcoming messages from the DW (greetings, ALPH price, fun fact...).

- [x] #298
- [x] #299

**Comment by nop33** [comment]
After deciding to go with Tanstack and offline storage, this is not needed anymore.
