### ISSUE TITLE
Improve loading of NFTs display

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#28]
- [ ] We could show some loading animation while the images are loading
- [x] Make sure there are no empty spaces. @h0ngcha0 reported:
<details><summary>Sometimes there are some empty spots on the NFT tab</summary>

![image](https://github.com/alephium/mobile-wallet/assets/1579899/8f43d7c6-ae09-4dc2-87d2-753e9e11cc4c)

</details>

**Comment by mvaivre** [comment]
@nop33 we may close that soon?

**Comment by nop33** [comment]
The first subtask is not yet completed.

**Comment by nop33** [comment]
As [discussed on Slack](https://alephium.slack.com/archives/C01B3D7HXAT/p1719213640751289), as of now, in the mobile and desktop wallet as well as the explorer we pass the [`NFTTokenUriMetaData.image`](https://github.com/alephium/alephium-web3/blob/cfe659e94d10bb20497d60a72c2c6f17f9e5f474/packages/web3/src/api/types.ts#L259-L267) string directly to the image component (`<img src={nft.image} />` for desktop wallet & explorer or `<Image source={{ uri: nft.image }} />` for mobile wallet). 

The image can potentially be a very large file. This gets especially alarming when we display a list of NFTs, where many can be a huge size, all displayed in the same screen at the same time.

The approach that Deadrare is using is the following:

They fetch all images through their image resizing service, which has has a CDN (Google Cloud CDN) infront of it for fast cached image retrieval.

Their image resizing service is available at https://image.deadrare.io/. It is a simple Node.JS server of 92 LoC that uses Sharp: https://sharp.pixelplumbing.com/

This is an example of how they would load an NFT that has the following as its image property:
- https://arweave.net/pur_d_ASLCJUj8-2Gfj7DG1fjr1C-c31iE9oGlaovqQ/14.png
- https://image.deadrare.io/?source=https://arweave.net/pur_d_ASLCJUj8-2Gfj7DG1fjr1C-c31iE9oGlaovqQ/14.png&width=800&height=800&fit=cover&position=centre&upscale=true&pixelArt=false&w=3840&q=75

A recommendation is that:
> “You don’t want to be serving the default image size in a list view, they can be massive.”

From our perspective, we don't want to use or maintain such a backend service because we want the wallets to not depend on external services such as the explorer backend.

If we want to not load the default image sizes for each NFT we need to brainstorm. Maybe do some image resizing and caching on the client side, while loading the default image size in the background, before the user opens the NFT displays.
