### ISSUE TITLE
I entered in my old wallet's recovery phrase, and it still created a new wallet for me. I need help 

### ISSUE THREAD

**Issue by justaNinjaWithARocketLauncher** [alephium/alephium-frontend#290]
So i need help recovering my old alephium wallet, i had a big chunk of my assets in there, i was able to find the recovery phrase, but when i typed it in, it still made a whole new wallet instead of bringing my old one back, please help

**Comment by nop33** [comment]
1. Which version are you using
2. Which network are you connected to? Mainnet?
3. Did you try using the address discovery feature?
4. Does the same issue happen if you restore the recovery phrase in the mobile wallet?
