### ISSUE TITLE
It's impossible to cancel a FaceID auth

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#32]
Cancelling a FaceID (or fingerprint ID for that matter) authentication makes the app try again by re-prompting the authentication UI.

Cancelling a biometric auth should probably prompt the pin screen.

**Comment by nop33** [comment]
Alright, thanks for testing. Yes, fallback to pin would be an option.

**Comment by nop33** [comment]
@mvaivre This is probably addressed with the new authentication flow (Uniswap)?

**Comment by nop33** [comment]
@mvaivre

**Comment by nop33** [comment]
@mvaivre is this still an issue with the new auth flow?

**Comment by mvaivre** [comment]
It's not! 🙃
