### ISSUE TITLE
App crashes when connecting to a dApp

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#391]
https://discord.com/channels/747741246667227157/747998352842686545/1213153149989167164

One guess is that this happens when connecting with an address that has many NFTs. It's possible that 1.0.6 fixes this.

Possibly related issue:
- https://github.com/alephium/alephium-frontend/issues/28

**Comment by nop33** [comment]
I noticed that Phantom maintains a fork of https://github.com/phantom/react-native-fast-image 
https://github.com/DylanVann/react-native-fast-image

**Comment by nop33** [comment]
We are using `expo-image` that is better maintained that https://github.com/DylanVann/react-native-fast-image

**Comment by nop33** [comment]
The crash might be happening because we use `prefetch` which stores data in memory. But if we don't use it, image loading is so slow... There must be a solution somewhere..

https://docs.expo.dev/versions/latest/sdk/image/#prefetchurls-cachepolicy

**Comment by nop33** [comment]
We should probably use a `FlatList` for loading the NFTs grid. FlatLists should be their own screen, however. @mvaivre I remember you had some ideas on moving NFTs to their own screen.

**Comment by mvaivre** [comment]
> I remember you had some ideas on moving NFTs to their own screen.

Yep, starting working on some early designs as a side task. I hope to be able to focus more on this next week.
<img width="411" alt="image" src="https://github.com/alephium/alephium-frontend/assets/6715943/496bf71b-a143-4f60-a273-8f975a6f50fc">
