### ISSUE TITLE
Cannot export last 12 months of txs in explorer

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#401]
Explorer returns `400` error.

**Comment by mvaivre** [comment]
Might be related to this year being a leap year.
I discussed with @tdroxler, we'll allow to fetch max 367 days instead of the current 365 days.

**Comment by nop33** [comment]
The bug is still there btw. Still getting 400 in both testnet and mainnet.

**Comment by nop33** [comment]
Fixed after latest explorer backend deployment
