### ISSUE TITLE
Add AUD (Australian Dollar) as fiat currency

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#422]
### Discussed in https://github.com/alephium/alephium-frontend/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **nit27** March  8, 2024</sup>
G'day mate 🤙

Since I found many fiat currencies on DW & MW, but there is still no AUD (Australian Dollar). Therefore, I wish you could add AUD as fiat display for spreading the awesome alephium project to Aussies 🇦🇺

Many thanks. Cheers!</div>

**Comment by nop33** [comment]
@tdroxler lemme know once you add the currency on explorer backend :)

**Comment by nit27** [comment]
Hi, Aussies are still wating for AUD 🇦🇺. Any plan for adding AUD fiat display to explorer backend?

**Comment by tdroxler** [comment]
@nit27 @nop33 sorry it's already there but forgot to comment here:

```bash
curl -X 'POST' \
  'https://backend.mainnet.alephium.org/market/prices?currency=aud' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '[
  "ALPH",
  "USDC",
  "USDT",
  "WBTC",
  "WETH",
  "DAI",
  "AYIN"
]'

[
  3.22937149387,
  1.52400507135,
  1.52305553548,
  94973.812114031,
  4842.506648729291,
  1.52400507135,
  25.61183102151
]
```

**Comment by nit27** [comment]
Thanks for letting us know :-)

**Comment by nop33** [comment]
Thanks for the update. PR ready: https://github.com/alephium/alephium-frontend/pull/549
