### ISSUE TITLE
Cannot access wallet after disabling Walletconnect

### ISSUE THREAD

**Issue by ErgoTester** [alephium/alephium-frontend#464]
mobile wallet android
disabled walletconnect and the app got reset

**Comment by nop33** [comment]
I believe this has nothing to do with WalletConnect and that it is rather that the update from 1.0.6 to 1.0.7 caused this. Specifically, these 2 commits might be related:
- https://github.com/alephium/alephium-frontend/commit/11d48cc3acf691395b3016e545a75092826c52b6
- https://github.com/alephium/alephium-frontend/commit/1ec19d10cf91b12be244b4fed9de565be656a1fc

Even though we tested thoroughly in the internal release phase, as well as in the beta phase, we didn't hit this issue. However, I suspect that this issue happens only in the case where the app is active (running in memory) and the user updates from Google Play.
