### ISSUE TITLE
Use the global "retry" wrapper from RTK Query

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#497]
As of today, we rely on using `exponentialBackoffFetchRetry` when creating our clients (explorer and node). 
In the future, we want to use the recommended RTK Query method, ie. wrap our base query with their `retry` function. See [here](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-retries).

**Comment by nop33** [comment]
Not gonna use it if we go for Tanstack. Closing.
