### ISSUE TITLE
Research translations management tool

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#50]
We are very lucky to recently have received an influx of contributors who are willing to translate our project!

This poses some new problems:
1. Our translators are not [familiar](https://user-images.githubusercontent.com/1579899/223175126-e50b2e3f-65a3-42a0-be2b-50e7b1e0f675.png) with git and GitHub workflows (PRs, [reviews](https://github.com/alephium/desktop-wallet/pull/531#pullrequestreview-1328254593), branches, [rebase](https://github.com/alephium/desktop-wallet/pull/527#issuecomment-1436600732), merge)
2. Our translation files are stored in JSON format. Our translators are not familiar with JSON and might create a PR with a [corrupted](https://github.com/alephium/desktop-wallet/pull/547/files) structure.
3. Providing translations requires apart from creating a JSON translation file to also [update pieces of code](https://github.com/alephium/desktop-wallet#adding-new-translation) to pick up this new file and enable the translation.

Maybe it's a good time to look into translation management tools.

Some initial research:
- https://locize.com/ (free for open-source projects - need to verify eligibility, found through the https://react.i18next.com/ docs, provides awesome integration with our tooling, but I don't like that the content is managed in their servers and not on GitHub)
- https://www.transifex.com/ (free for open-source projects - need to verify eligibility. This tool is used by the open-source project I was working on while at CERN, check out their [contribution guide](https://github.com/indico/indico/blob/master/CONTRIBUTING.md#translation-earth_asia))

My personal requirements would be:
- Minimise time required by devs to integrate new language
- Minimise time required by devs to register new translation strings when developing new UIs (currently, every time there's a new string, the dev needs to create a key-value pair in EVERY translation JSON file, which is cumbersome) 
- Provide UX friendly tool for translator who is unfamiliar with git(hub)
- Allow for review workflows
- Host translations on GitHub

WDYT?

**Comment by mvaivre** [comment]
I didn't feel like this is something we need, as the community was able to contribute nicely to translations.
We could close this, WDYT @nop33 ?

**Comment by nop33** [comment]
I disagree. There were many times that I had to go and clean up their PRs because of broken Yaml/JSON. As mentioned in the issue, translators are not necessarily familiar with git/GitHub/Yaml/JSON (and they shouldn't be, their job is linguistics, not tech). Even though it's not a high priority, I still think it's something we need. I've open to having my mind changed :)

**Comment by nop33** [comment]
Uniswap uses react-i18next (like we do) which given a list of JSON files (one for each language) it takes care of updating the texts in the React components when the user selects a language. They store their JSON files in a [shared package](https://github.com/Uniswap/interface/tree/main/packages/uniswap/src/i18n) called uniswap. We currently store the JSON files separate for each of our projects ([desktop wallet](https://github.com/alephium/alephium-frontend/tree/next/apps/desktop-wallet/locales), [explorer](https://github.com/alephium/alephium-frontend/tree/next/apps/explorer/locales)).
As a backend for translations I see that they use https://crowdin.com/ through these [npm scripts](https://github.com/Uniswap/interface/blob/main/package.json#L106-L109):

```
"i18n:_upload": "crowdin upload --token=$CROWDIN_ACCESS_TOKEN",
"i18n:upload": "dotenv -e .env.defaults -c -- yarn run i18n:_upload",
"i18n:_download": "crowdin download --token=$CROWDIN_ACCESS_TOKEN",
"i18n:download": "dotenv -e .env.defaults -c -- yarn run i18n:_download",
```

Useful guides:
- https://dev.to/adrai/how-to-properly-internationalize-a-react-application-using-i18next-3hdb
- https://www.transifex.com/blog/2023/react-localization-with-i18next/

**Comment by nop33** [comment]
We agreed to proceed with [Crowdin](https://crowdin.com/). Closing.
