### ISSUE TITLE
The contract call displayed when using the DEX is wrong on Desktop wallet

### ISSUE THREAD

**Issue by VDAODAO** [alephium/alephium-frontend#518]
**The contract call displayed when using the DEX is wrong on Desktop wallet**

It shows what i'm going to receive, and not what i'm sending. 

<img width="642" alt="Capture d’écran 2024-04-22 à 15 00 41" src="https://github.com/alephium/alephium-frontend/assets/42373571/112e3451-4613-4562-958b-f5cde005bafe">

It should be similar/coherent on mobile & desktop. 

Mobile shows what I'm sending.

![IMG_2509](https://github.com/alephium/alephium-frontend/assets/42373571/b0697fff-cd0d-4a86-aaa0-089fd3a2ae45)

**To Reproduce**

Connect to AYIN through walletconnect and do a transaction. 

What i'm talking about is the confirmation screen.

**Expected behavior**

**Screenshots**

**Environment**

- desktop wallet 2.2.5 On mac

**Additional context**

**Comment by VDAODAO** [comment]
Ok now this is weird, i since tested it again in 2.2.4 & 2.2.5 and it gave me the proper screen

<img width="580" alt="Capture d’écran 2024-04-22 à 18 03 36" src="https://github.com/alephium/alephium-frontend/assets/42373571/4401e2f3-7568-4444-baf3-1b26ab9eb922">
<img width="608" alt="Capture d’écran 2024-04-22 à 18 04 56" src="https://github.com/alephium/alephium-frontend/assets/42373571/77149257-2f95-41a7-93d6-9182ea727a90">

**Comment by nop33** [comment]
Let's consider it resolved, but keep an eye on it! Thanks!
