### ISSUE TITLE
Download-percentage is inconsistent during download of upgrade 

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/alephium-frontend#59]
**Describe the bug**
@nit27 just found an issue when the desktop app runs ‘auto update’. It showed that the dowloaded calculating percentage somehow went incorrectly. 

**Expected behavior**
percentage display should be consistent 

**Screenshots**

https://user-images.githubusercontent.com/3484593/224639095-028c2023-7195-4d00-8085-292cab963e4b.mp4

**Environment**
- Internet connection is fine. 
- MacOS 13.2.1

**Additional context**
- issue happened auto update from v1.5.2 to v1.5.3

**Comment by nit27** [comment]
The bug was fixed after version v1.5.3. 
Sorry I forgot closing the ticket.
