### ISSUE TITLE
Store already confirmed txs and historical data locally

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#60]
We currently have 2 features that (potentially) require the knowledge of the whole transaction history for all addresses of the wallet in order to work correctly. Those are:
1. Historical data on price: https://github.com/alephium/desktop-wallet/issues/587
2. Future unlock schedule: https://github.com/alephium/alephium-frontend/issues/44

Wouldn't it make sense that the wallet stores locally in an encrypted file(s) all address transaction data that has been recorded on the blockchain and there is no way it gets changed?

Ideas:
- Only store transactions that have `X` confirmation (or are older than 24h or sth)
- On wallet start-up, fetch all new transactions and update store

Benefits:
- Fewer requests to the explorer backend service
- Better UX since transaction pagination will not need to reach to a server (we could implement infinite scrolling)
- Can implement feature 1
- Can implement feature 2

@mvaivre, @tdroxler, what are your thoughts on this?

Some quick math: An average tx with 2 inputs, 4 outputs, some ALPH and some tokens takes about ~2'500 characters (with a [simple compression](http://www.unit-conversion.info/texttools/compress/) it can get down to 1'200 characters) so that's about 1KB per tx.

Open questions:
- How many txs does the larger ever Alephium wallet has?
- Is the performance of the electon app get affected when the Redux state grows a lot? (this is not inherently a potential problem of this proposal, a user can already click "See more" as many times as they want to load all their history)
- What other alternative proposals are there for implementing feature 1 and 2?

**Comment by nop33** [comment]
There have been several discussions within the team, so I will summarise everything here:

@polarker and @tdroxler came to agree with the original idea of this issue: **Store already confirmed txs locally**.

Additionally, they propose that since **everything is derived from transactions data**, we can move the computation load from the explorer backend to the wallet client side. Having all transaction history we can then calculate address balances, token balances, historical balances, basically everything that we use the explorer backend atm, without needing to query the backend.

## Concerns
1. **Too much data for the client to store**: To address this, we could use a pruning technique: Since data in the blockchain are immutable, we can compute the state of the app and persist the computer values in local storage. The extension wallet uses this technique. We could extract core computation functions to the SDK to share them amongst the wallets. The app state could store the `latest_tx_hash` that it has taken into account for the computed state. On app launch, it could query the explorer backend to say: 
   > _"This is the last tx hash I am aware of, give me all new transactions that took place since then"_.
   
   The app would re-calculate its state and update.
2. **Mobile devices are not very powerful**: Consider someone restoring their mining wallet on their Android phone (not advised, but possible). The app will query transactions starting from Genesis and process them. There are high chance that it cannot store all data in RAM before processing them, so a technique for batch processing will need to be implemented.
3. ...?

**Comment by tdroxler** [comment]
I think stuff like balance could still be called from the explorer-backend, for example for the mobile wallet it's better so we can quickly showing the balance when opening the wallet. The download of the txs could be done in background and slowly show additional information when it's there

**Comment by nop33** [comment]
Closing in favor or https://github.com/alephium/alephium-frontend/issues/126
