### ISSUE TITLE
Update desktop wallet without asking user to click "Update"

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#618]
As discussed offline, we want to implement a similar update strategy as Slack has: When there is a new update, it gets downloaded in the background and it gets installed next time the app launches again. This will help us keep our users' versions up to date.

Ideas:
1. We could display a progress bar as a snackbar message when the app is launched and a download starts automatically
2. We could display a second snackbar saying that the download was completed that the app will be update next time it is launched again.

**Comment by mvaivre** [comment]
And I would add to this a button to manually "restart" the wallet to install the update.

Actually, that's exactly how bloom is doing it (except that they still asks if the user wants to download it, first): 
<img width="405" alt="image" src="https://github.com/alephium/alephium-frontend/assets/6715943/297aeed9-e21c-44dd-bda0-8e02922fc861">

<img width="387" alt="image" src="https://github.com/alephium/alephium-frontend/assets/6715943/6c036ede-7ab0-4896-8537-6bb48e535f74">

**Comment by nop33** [comment]
Seems like we are on the right path 😉
