### ISSUE TITLE
Alephium Wallet not sending

### ISSUE THREAD

**Issue by bullfx** [alephium/alephium-frontend#642]
Hi, My Wallet is not openning send dialog it was working until yesterday

**Comment by mvaivre** [comment]
Is this still an issue @bullfx?

**Comment by bullfx** [comment]
found a way...may be because I had 2 addressess but main link is still not oppening send window


    On Monday, 15 July 2024 at 11:45:39 pm AWST, Mikaël Vaivre ***@***.***> wrote:  
 
 


Is this still an issue @bullfx?
