### ISSUE TITLE
[MW] Error displaying characters in Transaction history

### ISSUE THREAD

**Issue by nit27** [alephium/alephium-frontend#719]
**Describe the bug**
The characters of `Amount` has been broken down when there are many numbers of assets.

**To Reproduce**
1. Navigate to `Transfers` tab.
2. Select any transaction history with long numbers (or not sure it happens with assets with long characters).

**Expected behavior**
Maybe it should shorten the number of asset amounts. e.g: 9.99999999999999999999 -> 9.9999

**Screenshots**
![File 06-07-2024 at 16 09 39](https://github.com/alephium/alephium-frontend/assets/95131051/ad591577-4563-4970-a1ef-82b791090b17)
![File 06-07-2024 at 16 09 39 2](https://github.com/alephium/alephium-frontend/assets/95131051/c435e359-3f0a-4151-82ef-3ab0c7767460)

**Environment**
- ios: 17.5.1
- Mobile Wallet (ios) v1.1.1, lang: EN

**Comment by nop33** [comment]
Fixed in the latest release: 1.1.11.
Closing.
