### ISSUE TITLE
[DW] Losing metadata of address labels

### ISSUE THREAD

**Issue by nit27** [alephium/alephium-frontend#741]
As title, the issue is found at `Overview`, `Transfers`, and `Addresses`

<img width="750" alt="Screenshot 2024-07-17 at 14 26 46" src="https://github.com/user-attachments/assets/a5621b16-11a4-417e-98b5-0e7da705dbeb">

As you can see although they're losing their names of label, they also show the colour and they are in the rectangles  

<img width="350" alt="Screenshot 2024-07-17 at 14 26 21" src="https://github.com/user-attachments/assets/6d2779bc-4ec2-4712-83b9-f3db9735bc19">

<img width="350" alt="Screenshot 2024-07-17 at 14 26 07" src="https://github.com/user-attachments/assets/abc2c173-8c4e-40ac-97a1-02f3c5650e03">

Environment:
- MacOS 13.6.7
- DW 2.3.6

**Comment by nop33** [comment]
Is this a passphrase wallet?

**Comment by nop33** [comment]
We are planning on adding further explanations in the UI:

- https://github.com/alephium/alephium-frontend/issues/42

**Comment by nit27** [comment]
No, it isn't. The wallet only created by a seed phrase.

Hmm, you made me notice that there is no the `Default address` on top right as usual. Strange.

**Comment by nit27** [comment]
- I try to label them again, but cannot. The wallet doesn't response for `Address options` to label an address when I hit to the button `Settings`.
<img width="450" alt="Screenshot 2024-07-17 at 15 28 34" src="https://github.com/user-attachments/assets/150f1fbb-0c53-45ee-a000-d2caf33c2676">  

-----
- Also try to create a new wallet with new seed, the issue is gone (and the `Default address` on the top right comes back 😅

**Comment by nop33** [comment]
Hm, looks like the default address was "forgotten" somehow...

**Comment by mvaivre** [comment]
I encountered this once, but I thought it was because of a corrupted state in dev mode. It was indeed because the default address was not defined.

**Comment by nit27** [comment]
I've just re-installed my MacOS (made sure my computer was not compromised) and re-imported the wallets. The issue happened again with **the 1st seed**, but the **2nd seed** 🤔. Also seen that the `Send` button of the 1st wallet didn't response. Therefore, I removed the wallet with the 1st seed. Re-imported the 1st seed and now all wallets works temporarily fine.

*p.s: Multiple wallets on Linux doesn't cause this issue.*

**Comment by nop33** [comment]
We need to look at migration scripts and all places where we update the address metadata to find the source of the bug.

**Comment by nop33** [comment]
@xbabyx @nit27 can you please check if the latest version (2.3.7) fixes the problem of the missing default address? Thank you!

**Comment by xbabyx** [comment]
> @xbabyx @nit27 can you please check if the latest version (2.3.7) fixes the problem of the missing default address? Thank you!

Great work @nop33 !

I've tested it on my main PC, and on a Virtual Machine that had an Alephium wallet with this issue exactly.

I made sure that the wallet has a "missing Default Address", updated to 2.3.7, restarted and the Default Address was automatically applied and I could use all features back again! ❤️

**Comment by nit27** [comment]
> @xbabyx @nit27 can you please check if the latest version (2.3.7) fixes the problem of the missing default address? Thank you!

After being updated to **v2.3.7**, the `Default address` comes back, `Send` function works fine, and this issue is addressed 🤝 Great work @nop33 and the team 🚀

<img width="1198" alt="Screenshot 2024-08-14 at 20 25 56" src="https://github.com/user-attachments/assets/709baa46-a9c1-44f5-b88b-2c890a8e276e">
