### ISSUE TITLE
Unable to unlock wallet: Cannot read properties of undefined (reading 'transactions')

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#752]
`Encountered error while syncing your address' data - Cannot read properties of undefined (reading 'transactions')`

A user got the error after using the bridge successfully.
There's a couple of place which can induce this error, there's probably something wrong when storing addresses data (address object is undefined). TBD.

Continuing: just witnessed an error in PH: `Could not discover addresses`. If this is the same user, something may be fishy in `discoverAndCacheActiveAddresses`.

**Comment by nop33** [comment]
What is PH?

**Comment by nop33** [comment]
> Encountered error while syncing your address' data

This means that for whatever reason, the wallet could not sync address data (network error, too many 429, etc). Maybe we have a part in the code that if the API request fails, the address is not created in our store, leading to this error.

**Comment by mvaivre** [comment]
> What is PH?
Sorry, PostHog
