### ISSUE TITLE
Add an explanation tooltip next to the SC amount

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#78]
Similar to the tooltip we show when adding the 0.001 ALPH storage rent, we should add a little explanation next to the amount shown when interaction with a contract.

**Comment by nop33** [comment]
What is SC? 😅 I already forgot

**Comment by nop33** [comment]
what is SC? 😆 @mvaivre

**Comment by nop33** [comment]
Seems like this is not important?
