### ISSUE TITLE
Introduce thumbnail generation & broader NFT video support

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#838]
Let's port the more generic and efficient solution from the explorer in DW, the one creating thumbnails and compatible with more video formats.

https://github.com/alephium/alephium-frontend/blob/next/apps/explorer/src/components/VideoThumbnail.tsx

**Comment by nop33** [comment]
This was merged into next in https://github.com/alephium/alephium-frontend/pull/925. Closing.
