### ISSUE TITLE
[EPIC] Display fiat prices of tokens in wallets

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#88]
Depends on https://github.com/alephium/alephium-frontend/issues/115

- [x] #243
- [x] #244

Other assets apart from bridged ones:
- Ayin

**Comment by nop33** [comment]
To fetch prices of more tokens we first need to fix the issue of not being able to fetch prices from CoinGeko: https://github.com/alephium/alephium-frontend/issues/115

**Comment by ElvisGAN777** [comment]
This is much needed at this point. I am onboarding normies and they are confounded as to why the value of their alternate tokens are not showing up in the total fiat balance.

**Comment by nop33** [comment]
Thanks for the feedback @ElvisGAN777. It is our highest priority task. It has been a tricky feature that required work from many teams. It will be released asap.

**Comment by ElvisGAN777** [comment]
Thanks @nop33 !
