### ISSUE TITLE
Improve private key management

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#9]
The function `deriveNewAddressData` is returning an `AddressKeyPair`

```ts
export type AddressKeyPair = {
  hash: string
  index: number
  publicKey: string
  privateKey: string
}
```

Having the private key in here could cause security issues (like storing it in clear text by mistake along with non critical data).

Cheng is suggesting that we could refactor the function so that we have a specialized function for returning the private keys, and another function for returning non-critical data like address, public key, group etc.

**Comment by nop33** [comment]
This is addressed in version 1.1.0. Closing.
