### ISSUE TITLE
blank page with 2.4.1

### ISSUE THREAD

**Issue by sacredland** [alephium/alephium-frontend#915]
After update, wallet open but just show a white blank page. 
![Capture d’écran du 2024-10-22 22-36-00](https://github.com/user-attachments/assets/9a7a1bb7-de97-4d53-8d12-40f690ad43d9)

**Comment by nop33** [comment]
Thank you, we are looking into it

**Comment by nop33** [comment]
We discovered that the white screen bug happens only to users who have set their auto-lock settings to "off".

**Comment by sacredland** [comment]
but now how can i acces to my wallet?

**Comment by nop33** [comment]
The new version fixes this. Can you try to update?
