### ISSUE TITLE
Alephium price

### ISSUE THREAD

**Issue by sacredland** [alephium/alephium-frontend#939]
On 2.3 we could see the market value of alephium on the main page. Now we need to go into adresse to get it. Can we bring it back to the main page for a quick view?

**Comment by nop33** [comment]
You can still see the ALPH price (and in fact the prices of all tokens we can get prices for) in the tokens table in the main page, the same page as the one that used to show the ALPH price.

![image](https://github.com/user-attachments/assets/fa19f7a0-7dd8-4187-8503-2dcfad44a7d8)

**Comment by sacredland** [comment]
Yes, but it needs more operations. on 2.3 it was just in front of you, nothing else to do.

**Comment by nop33** [comment]
What more operations are you referring to? The moment you unlock a wallet, the first item in the tokens list that you see is Alephium and the price is always displayed next to it. Isn't that the case?
